name    'alkivi-openvpn'
version '0.0.2'
source 'https://github.com/alkivi-sas/puppet-openvpn'
author 'alkivi'
license 'LGPLv3'
summary 'Controls openvpn server and clients'
description 'Setup openvpn server and clients, with some tools to quickly create new files'
project_page 'https://github.com/alkivi-sas/puppet-openvpn'
dependency 'puppetlabs/stdlib', '>3.x'
#dependency 'puppetlabs/concat', '1.0.0'
#dependency 'puppetlabs/apache', '>0.x'
dependency 'alkivi/alkivi_base', '>0.x'
dependency 'thias/sysctl', '>0.1.1'
