name    'alkivi-openvpn'
version '0.1.1'
source 'https://github.com/alkivi-sas/puppet-openvpn'
author 'alkivi'
license 'LGPLv3'
summary 'Controls openvpn server and clients'
description 'Setup openvpn server and clients, with some tools to quickly create new files'
project_page 'https://github.com/alkivi-sas/puppet-openvpn'
dependency 'puppetlabs/stdlib', '>=3.0.0'
dependency 'alkivi/alkivi_base', '>=0.1.0'
dependency 'thias/sysctl', '>0.1.1'
